Refactor Task
AY2223S2-CS2103-W17-1/tp pull request #97
Opened 2023-03-22 07:14 UTC by toh-xinyi

# Changes
- Create new enum to hold all possible `Task` statuses: `INPROGRESS`, `LATE`, `COMPLETE`
- Add `status` and hidden `creationDate` attributes to `Task` class
- Make `Task implement Comparable<Task>` to compare `Task` objects based on its `status` followed by `creationDate`
---
# Issues
- Resolves #93

2023-03-22 15:34 UTC, CarrieLi1015 commented
LGTM! Nice work :))

2023-03-24 17:30 UTC, astraxq requested changes
Hmm, I have yet to check the rest but I've realise quite a major bug:

- Adding tasks isn't reflected on the GUI, you might need to check on this. 

![Uploading image.png…]()

2023-03-25 01:46 UTC, toh-xinyi commented on src/main/java/seedu/address/logic/commands/DeleteTaskCommand.java
> +        requireAllNonNull(studentIndex, taskIndex);
Good point. We can do so next week.

2023-03-25 01:52 UTC, toh-xinyi commented
> Hmm, I have yet to check the rest but I've realise quite a major bug:
> 
> * Adding tasks isn't reflected on the GUI, you might need to check on this. [1st Image]
> * In addition, changing to another student doesn't reflect the change on the task list too. [2nd Image]
> 

@astraxq Oops, thanks for noticing, I forgot to change the name of an attribute in the fxml file. It should be fixed now. Thanks for your help

2023-03-27 08:08 UTC, astraxq approved these changes

2023-03-27 09:14 UTC, QQH0828 reviewed
LGTM! Good Work!

2023-03-27 09:14 UTC, merged